# SPDX-FileCopyrightText: 2024 The Input Leap Developers
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "ei-wlroots-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["env", "derive", "unicode", "string"] }
miette = { version = "7.2.0", features = ["fancy"] }
reis = { version = "0.2.0", features = ["tokio"] }
thiserror = "1.0.63"
tokio = { version = "1.39.3", features = ["fs", "process", "rt", "rt-multi-thread"] }
wayland-client = "0.31.1"
wayland-protocols = { version = "0.32.3", features = ["client", "unstable"] }
wayland-protocols-misc = { version = "0.3.3", features = ["client"] }
wayland-protocols-wlr = { version = "0.3.3", features = ["client"] }
