# SPDX-FileCopyrightText: 2024 The Input Leap Developers
#
# SPDX-License-Identifier: Apache-2.0

---
name: Nix packaging tests

on:
  push:
  pull_request:

jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: cachix/install-nix-action@v30
      - name: Check Nix Flake
        run: nix flake check --print-build-logs --all-systems --impure

  check-nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: cachix/install-nix-action@v30
      - name: Build package
        run: nix build --print-build-logs --impure
