# SPDX-FileCopyrightText: 2024 The Input Leap Developers
# SPDX-FileCopyrightText: 2024 The Input Leap Team
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: GPL-3.0-or-later

name: REUSE Compliance workflow

on:
  pull_request:

jobs:
  test-reuse-compliance:
    name: Test the commit for REUSE Compliance.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: fsfe/reuse-action@v4
